### ISSUE TITLE
[Upstream Change Adjustment] Adjust `linkedin_pages__posts` to account for deprecated table `ugc_post_share_content_media`

### ISSUE THREAD

**Issue by fivetran-avinash** [fivetran/dbt_linkedin_pages#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`ugc_post_share_content_media` was deprecated [internally in a recent release of Linkedin Pages](https://fivetran.com/docs/applications/linkedin-company-pages/changelog). This is causing errors for customers attempting to use Transformations on Linkedin Pages.

[Examining the new ERD](https://docs.google.com/presentation/d/1PbexBiOTxplv7TlmNZ7uNo8EDT2Lr5g0Ys_ealh4qzI/edit#slide=id.g311502b468_5_443), it's likely we will need to modify our join in `linkedin_pages__posts`.

### Relevant error log or model output

```shell
Transformations should run.
```

### Expected behavior

Standard to transformations: https://github.com/fivetran/dbt_linkedin_pages_source/blob/main/dbt_project.yml

### dbt Project configurations

standard to transformations: https://github.com/fivetran/dbt_linkedin_pages/blob/main/dbt_project.yml

### Package versions

packages:
  - package: fivetran/linkedin_pages
    version: [">=0.2.0", "<0.3.0"]

### What database are you using dbt with?

other (mention it in "Additional Context")

### dbt Version

What version transformations is running on.

### Additional Context

 https://fivetran.slack.com/archives/C02919TN9AT/p1695850062879859

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-catfritz** [comment]
I am picking up this issue, aiming to be completed in the next couple weeks.
