### ISSUE TITLE
[Bug] Package fivetran/linkedin_pages was not found in the package index Code: 10006

### ISSUE THREAD

**Issue by aljosja-online** [fivetran/dbt_linkedin_pages#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Including this in packages.yml:

package: fivetran/linkedin_pages
    version: [">=0.1.0", "<0.2.0"]

Results in the following error: Package fivetran/linkedin_pages was not found in the package index Code: 10006

### Expected Behavior

The Fivetran dbt package for linkedin_pages get installed

### What database are you using dbt with?

bigquery

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @aljosja-online thanks so much for creating this issue!

This package is actually not officially released yet. That is why you are seeing the dependency error. We are planning to officially release this package and have it be love on the hub by Jan 17th!

In the meantime, you can easily use this package by using the git syntax in your `packages.yml`. See how you can leverage that below 😄 

```yml
packages:
  - git: "https://github.com/fivetran/dbt_linkedin_pages"
```

**Comment by fivetran-joemarkiewicz** [comment]
@aljosja-online As of last week the official package is now live on the dbt hub! Feel free to use the dbt hub version when installing the package.

Let me know if you have any future questions 😄
